### ISSUE TITLE
Dev spring_profiles_active to set to mysql

### ISSUE THREAD

**Issue by ezYakaEagle442** [demo-thursday/azure-service-operator#1]
At [https://github.com/demo-thursday/azure-service-operator/blob/master/overlays/azure-dev/environment-patch.yaml](https://github.com/demo-thursday/azure-service-operator/blob/master/overlays/azure-dev/environment-patch.yaml) the spring_profiles_active shouldn'it be mysql so that SpringBoot loads then [application-mysql.properties](https://github.com/pittar/spring-petclinic/blob/master/src/main/resources/application-mysql.properties) ?

Also MYSQL_SERVER should be localhost then ?

**Comment by pittar** [comment]
@ezYakaEagle442 , you're right, the patch should be `mysql` not `azure` (for both dev and prod profiles).

As for the MYSQL_SERVER, it is set to localhost by default, the "prod" profile overrides it:
https://github.com/pittar/spring-petclinic/blob/azure/src/main/resources/application-mysql.properties

Thanks for the issue, I'll fix it later today.

**Comment by ezYakaEagle442** [comment]
@pittar in the application-mysql.properties there is the MYSQL_URL that is not overridden by the Prod Patch , it is a bit confusing.
I could understand that the Azure Profile has to be set in the Prod Patch.

 I understand that the [Spring Active profile](https://docs.spring.io/spring-boot/docs/2.5.x-SNAPSHOT/reference/html/howto.html#howto-set-active-spring-profiles) is named to spring_profiles_active to be set as a contrainer env. variable instead of being hard coded with the spring.profiles.active property .

**Comment by pittar** [comment]
Hey @ezYakaEagle442 ,

Sorry for the confusion.  Now that I've had a chance to actually sit down and look at the both repositories (this one, and the master branch of https://github.com/pittar/spring-petclinic), I don't think there should be any problem.

In the main petclinic repository under `/src/main/resources` there is a three files.  I think the confusing part is I left the "application-mysql.properties" file in there from the upstream "petclinic" example.  It isn't used for this demo, so I will delete it.

The only two files that apply and are used in this demo are:

- `application.properties` and
- `application-azure.properties`

The first file holds all the default values and is always included.  The 2nd file is only included when the `azure` profile is active (hence the patch with the env var `spring_profiles_active` and a value of `azure`).

So, if you look at the DEV patch, it will set the profile to `azure`, which will set the `MYSQL_SERVER` to `petclinicdb`.  This is the correct name, since that is the service name of the MySQL database that is deployed as a container in dev.

The PROD patch also sets the profile to `azure`, but sets the `MYSQL_SERVER` env var to the fully qualified name of the MySQL server that the Azure Service Operator has created.

I hope that helps sort things out for you.  I'll delete `application-mysql.properties` since it's just confusing to have it left in the project.

I'm also spinning up a new ARO cluster so I can double check the process before I close the ticket.

**Comment by pittar** [comment]
Ok.  I just finished running through the demo and it does work as expected.  I haven't deleted the "application-mysql.properties" yet, as I do like to use that locally sometimes.  I think what I will do is make a new branch of the "petclinic" app called "azure-service-operator", then delete the extra file over there.  Then I'll point the buildconfig to that branch.

Hope that clears things up!

FYI, I updated my ARO cluster to 4.6.8 before installing the azure service operator or the demo.
